- name: Deploy frontend to Azure
on:
  push:	
    branches:	
      - azure-deploy-test
jobs:
  deploy:
    name: Deploy frontend to Azure
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: frontend-master
        FOLDER: frontend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}